package:
  title: Norton Design System Sassdoc
  description: Styles, components, and utilities for building accessible, responsive products.

groups:
  main: Main API
  config: Config
  color: Color
  typography: Typography
  spacing: Spacing
  motion: Motion
  device: Device
  reset: Reset
  accessibility: Accessibility
  miscellaneous: Miscellaneous
  helpers: Helpers
  utilities: Utilities
