/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	guides: [
		'guides/index',
		{
			type: 'category',
			label: 'Development',
			collapsed: true,
			items: [
				'guides/dev/getting-started',
				'guides/dev/stylesheet-setup',
				'guides/dev/writing-css',
				'guides/dev/core-api',
				'guides/dev/react-api',
				// 'principles',
				// 'migration',
			],
		},
		'guides/usable-writing-guidelines',
	],
	foundations: [
		'foundations/index',
		'foundations/accessibility',
		'foundations/design-tokens',
		'foundations/color',
		'foundations/typography',
		// 'foundations/spacing',
		'foundations/motion',
	],
	components: [
		'components/index',
		// 'components/accordion',
		'components/badge',
		'components/button',
		'components/callout',
		'components/checkbox',
		'components/choice-field',
		'components/disclosure',
		'components/dropdown',
		// 'components/icon',
		// 'components/layout-grid',
		'components/link',
		'components/modal',
		'components/popover',
		'components/progress-bar',
		'components/radio-group',
		'components/spinner',
		'components/step-indicator',
		'components/switch',
		'components/table',
		'components/tabs',
		'components/tag',
		'components/text-field',
		'components/tooltip',
		'components/react-providers',
	],
};

module.exports = sidebars;
