module.exports = {
	guides: [
		'guides/index',
		{
			type: 'category',
			label: 'Developer',
			collapsed: false,
			items: [
				'guides/dev/introduction',
				'guides/dev/getting-started',
				// 'guides/dev/styling',
				// 'guides/dev/hooks',
				// 'principles',
				// 'migration',
			],
		},
	],
	foundations: [
		'foundations/index',
		'foundations/accessibility',
		'foundations/design-tokens',
		'foundations/color',
		'foundations/typography',
		'foundations/spacing',
		'foundations/motion',
	],
	components: [
		'components/index',
		// 'components/accordion',
		'components/button',
		'components/checkbox',
		'components/choice-field',
		'components/disclosure',
		'components/dropdown',
		// 'components/icon',
		// 'components/layout-grid',
		'components/link',
		'components/modal',
		'components/radio-group',
		'components/switch',
		'components/text-field',
		'components/tooltip',
	],
};
