# cSpell:ignore coverallsapp
name: Integration

on:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_VERSION: 18

jobs:
  build:
    name: Build library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Install 📦
        run: npm ci
      - name: Build 🔧
        run: npm run build

  docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Install 📦
        run: npm ci
      - name: Build Sassdoc 💄
        run: npm run build:sassdoc
      - name: Build Storybook 📚
        run: npm run build:stories
      - name: Build docs 📄
        run: npm run build:docs
        env:
          BASE_URL: /design-system/

  cspell:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Install 📦
        run: npm ci
      - name: CSpell ✏️
        run: npm run cspell

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Install 📦
        run: npm ci
      - name: ESLint ✨
        run: npm run lint:es

  stylelint:
    name: Stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Install 📦
        run: npm ci
      - name: Stylelint ✨
        run: npm run lint:style

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Install 📦
        run: npm ci
      - name: Prettier ✨
        run: npm run lint:prettier

  test:
    name: Test | Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [14, 16, 18]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
      - name: Update npm
        if: ${{ env.NODE_VERSION == 14 }}
        run: npm i -g npm@7
      - name: Install 📦
        run: npm ci
      - name: Test 🧪
        run: npm run coverage
      - name: Codecov ☂
        uses: codecov/codecov-action@v3
        if: ${{ matrix.node == env.NODE_VERSION }}
        with:
          directory: coverage
