name: GitHub Pages

on:
  push:
    branches:
      - main

env:
  FORCE_COLOR: 2
  NODE_VERSION: 14
  NPM_VERSION: 8

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: Update npm
        run: npm i -g npm@${{ env.NPM_VERSION }}
      - name: Install 📦
        run: npm install
      - name: Build Sassdoc 💄
        run: npm run build:sassdoc
      - name: Build Storybook 📚
        run: npm run build:stories
      - name: Build docs 📄
        run: npm run build:docs
        env:
          BASE_URL: /design-system/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
