name: GitHub Pages

on:
  push:
    branches:
      - $default-branch

env:
  NODE_VERSION: 18

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Install 📦
        run: npm ci
      - name: Build Sassdoc 💄
        run: npm run build:sassdoc
      - name: Build Storybook 📚
        run: npm run build:stories
      - name: Build docs 📄
        run: npm run build:docs
        env:
          BASE_URL: /design-system/
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy 🚀
        id: deployment
        uses: actions/deploy-pages@v2
